tickers:
  - BMO.TO
  - ENB.TO
  - RY.TO
  - TD.TO
  - TRP.TO

risk_aversion: 2.5

views:
  # Absolute
  # View 1: BMO.TO will have an absolute excess return of
  # 5.25% (Confidence of View = 25%).
  - title: View 1
    type: absolute
    asset: BMO.TO
    expected_return: 0.0525 # Negative for going down
    confidence: 0.25
  # Relative
  # View 2: ENB.TO will outperform RY.TO by 3.75% (Confidence of View = 50%).
  - title: View 2
    type: relative
    long: ENB.TO
    short: RY.TO
    expected_outperformance: 0.0375
    confidence: 0.5
  # Multi-asset relative
  # TD.TO AND TRP.TO together will outperform RY.TO by 15% (Confidence of View = 70%).
  - id: V3
    type: relative
    long:
      - TD.TO
      - TRP.TO
    short:
      - RY.TO
    expected_outperformance: 0.15
    confidence: 0.7
